modLoader="javafml"
loaderVersion="[24,)"
issueTrackerURL="https://github.com/minecraftabnormals/Upgrade-Aquatic/issues"

[[mods]]
    modId="upgrade_aquatic"
    namespace="upgrade_aquatic"
    version="1.0"
    displayName="Upgrade Aquatic"
    authors="SmellyModder, Cameron"
    description=''''''
    displayURL=""
    [[dependencies.upgrade_aquatic]]
        modId="forge"
        mandatory=true
        versionRange="[${forge_version},)"
        ordering="NONE"
        side="BOTH"